{
  "log": {
    "access": "/var/log/v2ray/access.log",
    "error": "/var/log/v2ray/error.log",
    "loglevel": "warning"
  },
  "inbounds": [
    {
      "tag": "in-shadow",
      "port": "1470-1475",
      "listen": "0.0.0.0",
      "protocol": "shadowsocks",
      "settings": {
        "method": "aes-256-gcm",
        "password": "SS_PASSWORD",
        "network": "tcp"
      }
    },
    {
      "port": 445,
      "tag": "in-vmess-nginx",
      "listen": "127.0.0.1",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "VMESS_UUID_NGINX",
            "alterId": 0,
            "security": "auto"
          }
        ]
      },
      "streamSettings": {
        "network": "ws" ,
        "wsSettings": {
          "path": "/"
        } ,
        "security": "none" ,
        "tcpSettings": {
          "header": {
            "type": "http" ,
            "response": {
              "version": "1.1" ,
              "status": "200" ,
              "reason": "OK" ,
              "headers": {
                "Content-Type": [
                  "application/octet-stream" ,
                  "application/x-msdownload" ,
                  "text/html" ,
                  "application/x-shockwave-flash"
                ] ,
                "Transfer-Encoding": [
                  "chunked"
                ] ,
                "Connection": [
                  "keep-alive"
                ] ,
                "Pragma": "no-cache"
              }
            }
          }
        }
      }
    },
    {
      "port": 1400,
      "tag": "in-vmess-ws",
      "listen": "0.0.0.0",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "VMESS_UUID_WS_1",
            "alterId": 0,
            "security": "auto"
          },
          {
            "id": "VMESS_UUID_WS_2",
            "alterId": 0,
            "security": "auto"
          }
        ]
      },
      "streamSettings":{
        "network":"ws"
      }
    },
    {
      "port": 1401,
      "tag": "in-vmess-tcp",
      "listen": "0.0.0.0",
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "VMESS_UUID_TCP_1",
            "alterId": 0,
            "security": "auto"
          },
          {
            "id": "VMESS_UUID_TCP_1",
            "alterId": 0,
            "security": "auto"
          }
        ]
      },
      "streamSettings": {
        "network": "tcp" ,
        "tcpSettings": {
          "header": {
            "type": "http",
            "response": {
              "version": "1.1",
              "status": "200",
              "reason": "OK",
              "headers": {
                "Content-Type": [
                  "application/octet-stream",
                  "video/mpeg",
                  "application/x-msdownload",
                  "text/html",
                  "application/x-shockwave-flash"
                ],
                "Transfer-Encoding": [
                  "chunked"
                ],
                "Connection": [
                  "keep-alive"
                ],
                "Pragma": "no-cache"
              }
            }
          }
        }
      }
    }
  ],
}